version: '3.2'

networks:
  bubble:
    external: true

services:
  api.backend.dev:
    container_name: api.backend.dev
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./backend:/usr/src/app
      - node_modules-backend:/usr/src/app/node_modules
    ports:
      - '3333:3333'
    networks:
      - bubble
  # api.frontend.dev:
  #   container_name: api.frontend.dev
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   volumes:
  #     - ./frontend:/app
  #     - node_modules-frontend:/app/node_modules
  #   ports:
  #     - '3000:3000'
  #   networks:
  #     - bubble

volumes:
  node_modules-backend:
  # node_modules-frontend:
